Bring ci.yml up to date (manually)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,41 +1,40 @@
-# This file is synced from dry-rb/template-gem repo
+# This file is synced from hanakai-rb/repo-sync
+
 name: CI
 
 on:
   push:
-    paths:
-      - ".github/workflows/ci.yml"
-      - "lib/**"
-      - "*.gemspec"
-      - "spec/**"
-      - "Rakefile"
-      - "Gemfile"
-      - "Gemfile.devtools"
-      - ".rubocop.yml"
-      - "project.yml"
+    branches: ["main", "release-*", "ci/*"]
+    tags: ["v*"]
   pull_request:
-    branches:
-      - main
-  create:
+    branches: ["main", "release-*"]
+  schedule:
+    - cron: "30 4 * * *"
 
 jobs:
   tests:
+    name: Tests (${{ matrix.ruby }})
+    permissions:
+      pull-requests: write
     runs-on: ubuntu-latest
-    name: Tests
+    continue-on-error: ${{ matrix.optional }}
     strategy:
       fail-fast: false
       matrix:
         ruby:
-        - "3.3"
-        - "3.2"
-        - "3.1"
-        - "3.0"
+          - "3.4"
+          - "3.3"
+          - "3.2"
+        optional: [false]
         include:
-          - ruby: "3.2"
+          - ruby: "3.4"
             coverage: "true"
+          - ruby: "jruby"
+            optional: true
+          - ruby: "4.0.0-preview2"
+            optional: true
     env:
       COVERAGE: ${{matrix.coverage}}
-      COVERAGE_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -47,25 +46,52 @@ jobs:
           ruby-version: ${{matrix.ruby}}
           bundler-cache: true
       - name: Run all tests
-        run: bundle exec rake
-  release:
-    runs-on: ubuntu-latest
-    if: contains(github.ref, 'tags') && github.event_name == 'create'
-    needs: tests
-    env:
-      GITHUB_LOGIN: dry-bot
-      GITHUB_TOKEN: ${{secrets.GH_PAT}}
-    steps:
-      - uses: actions/checkout@v3
-      - name: Install package dependencies
-        run: "[ -e $APT_DEPS ] || sudo apt-get install -y --no-install-recommends $APT_DEPS"
-      - name: Set up Ruby
-        uses: ruby/setup-ruby@v1
-        with:
-          ruby-version: 3.0
-      - name: Install dependencies
-        run: gem install ossy --no-document
-      - name: Trigger release workflow
+        id: test
         run: |
-          tag=$(echo $GITHUB_REF | cut -d / -f 3)
-          ossy gh w dry-rb/devtools release --payload "{\"tag\":\"$tag\",\"sha\":\"${{github.sha}}\",\"tag_creator\":\"$GITHUB_ACTOR\",\"repo\":\"$GITHUB_REPOSITORY\",\"repo_name\":\"${{github.event.repository.name}}\"}"
+          status=0
+          bundle exec rake || status=$?
+          if [ ${status} -ne 0 ] && [ "${{ matrix.optional }}" == "true" ]; then
+            echo "::warning::Optional matrix job failed."
+            echo "optional_fail=true" >> "${GITHUB_OUTPUT}"
+            echo "optional_fail_status=${status}" >> "${GITHUB_OUTPUT}"
+            exit 0  # Ignore error here to keep the green checkmark
+          fi
+          exit ${status}
+      - name: Add comment for optional failures
+        uses: thollander/actions-comment-pull-request@v3
+        if: ${{ matrix.optional && github.event.pull_request }}
+        with:
+          comment-tag: "${{ matrix.ruby }}-optional-failure-notice"
+          message: |
+            ℹ️ Optional job failed: Ruby ${{ matrix.ruby }}
+          mode: ${{ steps.test.outputs.optional_fail == 'true' && 'upsert' || 'delete' }}
+
+  workflow-keepalive:
+    if: github.event_name == 'schedule'
+    runs-on: ubuntu-latest
+    permissions:
+      actions: write
+    steps:
+      - uses: liskin/gh-workflow-keepalive@v1
+
+  # release:
+  #   runs-on: ubuntu-latest
+  #   if: github.ref_type == 'tag'
+  #   needs: tests
+  #   env:
+  #     GITHUB_LOGIN: dry-bot
+  #     GITHUB_TOKEN: ${{secrets.GH_PAT}}
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - name: Install package dependencies
+  #       run: "[ -e $APT_DEPS ] || sudo apt-get install -y --no-install-recommends $APT_DEPS"
+  #     - name: Set up Ruby
+  #       uses: ruby/setup-ruby@v1
+  #       with:
+  #         ruby-version: 3.3
+  #     - name: Install dependencies
+  #       run: gem install ossy --no-document
+  #     - name: Trigger release workflow
+  #       run: |
+  #         tag=$(echo $GITHUB_REF | cut -d / -f 3)
+  #         ossy gh w dry-rb/devtools release --payload "{\"tag\":\"$tag\",\"sha\":\"${{github.sha}}\",\"tag_creator\":\"$GITHUB_ACTOR\",\"repo\":\"$GITHUB_REPOSITORY\",\"repo_name\":\"${{github.event.repository.name}}\"}"
